// auth
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const IS_PHONE_SIGNUP_COMPLETE = "IS_PHONE_SIGNUP_COMPLETE";

// other
export const LOAD_STATES_CITIES = "LOAD_STATES_CITIES";

// modals
export const LOGIN_MODAL = "LOGIN_MODAL";
export const SIGNUP_MODAL = "SIGNUP_MODAL";
export const SIGNUP_WITH_PHONE_MODAL = "SIGNUP_WITH_PHONE_MODAL";
export const REQ_BOOKING_MODAL = "REQ_BOOKING_MODAL";
export const QA_MODAL = "QA_MODAL";
export const FEEDBACK_MODAL = "FEEDBACK_MODAL";
export const SHARE_MODAL = "SHARE_MODAL";
