# Generated by Django 4.0.3 on 2022-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_through',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=15),
        ),
    ]
