# Generated by Django 4.0.3 on 2022-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_booking_process_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
