# Generated by Django 4.0.3 on 2022-03-19 15:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_venue_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='venue',
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200, null=True),
        ),
    ]
