# Generated by Django 4.0.3 on 2022-03-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_remove_venue_amenities_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
            preserve_default=False,
        ),
    ]
