# Generated by Django 4.0.3 on 2022-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_amenity_name_venuephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('parking', 'Parking'), ('air-conditioning', 'Air conditioning')], max_length=50),
        ),
    ]
