# Generated by Django 4.0.3 on 2022-03-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_amenity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='slug',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.amenityname'),
        ),
    ]
