# Generated by Django 4.0.3 on 2022-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_alter_location_city_alter_location_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.AlterField(
            model_name='venuephoto',
            name='image',
            field=models.ImageField(upload_to='venues/photos/'),
        ),
    ]
