# Generated by Django 4.0.3 on 2022-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_remove_amenity_icon_alter_venuephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenityname',
            name='icon',
            field=models.ImageField(blank=True, upload_to='amenities/'),
        ),
    ]
