# Generated by Django 4.0.3 on 2022-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_amenityname_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
