# Generated by Django 4.0.3 on 2022-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_alter_location_city_alter_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='rent_by',
            field=models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='hour', max_length=25),
        ),
    ]
