# Generated by Django 4.0.3 on 2022-03-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_venue_rent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.amenityname'),
        ),
    ]
