# Generated by Django 4.0.3 on 2022-04-11 06:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_alter_amenity_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('name'), django.db.models.expressions.F('venue'), name='unique_amenity_venue'),
        ),
    ]
