# Generated by Django 4.0.3 on 2022-04-18 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_booking_admin_remarks'),
        ('venues', '0019_amenity_unique_amenity_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('user'), django.db.models.expressions.F('venue'), name='unique_review_venue'),
        ),
    ]
