# Generated by Django 4.0.3 on 2022-04-22 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_alter_venue_rent_alter_venue_rent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_type', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg'), ('both', 'both')], max_length=15)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPhoto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='venues/photos/food/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.restaurant')),
            ],
        ),
    ]
