# Generated by Django 4.0.3 on 2022-04-23 13:01

import api.venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_alter_foodphoto_image_alter_restaurant_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodphoto',
            name='image',
            field=models.ImageField(default=0, upload_to=api.venues.models.food_photo_path),
            preserve_default=False,
        ),
    ]
