# Generated by Django 4.0.3 on 2022-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_alter_foodphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='rent_by',
            field=models.CharField(blank=True, choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('plate', 'plate'), ('two people', 'two people')], max_length=25, null=True),
        ),
    ]
